---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(ggplot2)
library(here)
library(deSolve)
library(crone)
library(optimParallel)
library(doParallel)
library(doRNG)
library(arrow)
library(stringr)
library(parallel)
library(ggpubr)
library(DEoptim)
library(marqLevAlg)
```

```{r}
parameters_tsukushi <- c(R1 = 8.89*10^6, # slightly higher
                lambda = 3.7*10^5,
                mu = 0.025, 
                p = 8*10^-6, # doubled form original
                alpha = 1, 
                alphag = 2, 
                beta = 5.721, 
                mum = 48, 
                mug = 4, 
                I0 = 43.85965, 
                Ig0 = 0, 
                a = 150, 
                b = 100, 
                sp = 1,
                psin = 16.69234,
                psiw = 0.8431785,
                phin = 0.03520591, 
                phiw = 550.842,
                iota = 2.18*(10^6),
                rho = 0.2627156)

time_range <- seq(0, 20, by = 1e-3)
```


```{r}
source(here("functions/chabaudi_si_clean.R"))
```

# trying DE optim. works although slow
```{r}
res <- DEoptim(
    fn = chabaudi_si_clean, 
    control = list(trace = 1, parallelType = 1),
    lower = c(-1, -100, -1000, -5000),
    upper = c(1, 100, 1000, 5000),
    immunity = "tsukushi",
    parameters = parameters_tsukushi,
    time_range = time_range,
    cue = "I",
    log_cue = "log10",
    cue_range = seq(0, 6*(10^6), by = (6*(10^6))/5000),
    solver = "vode",
    neg = T)
```

# trying DE optim coinfection
```{r}
source(here("functions/co_infection_opt_do.R"))
source(here("functions/chabaudi_ci_clean.R"))
source(here("functions/co_infection_opt_alt.R"))
```

# Ig alone logged
note started at 0.5x4.
```{r}
ci_Ig_log_opt <- co_infection_opt_do(parameters_cr = c(0.359066,  -65.485796,  344.211487, -438.589440),
                             limit = 0.01,
                             model = chabaudi_ci_clean,
                             immunity = "tsukushi",
                             parameters = parameters_tsukushi,
                             time_range = time_range,
                             cue_1 = "Ig1",
                             cue_2 = "Ig2",
                             cue_range_1 = seq(0, log10(6*(10^6)), by = log10(6*(10^6))/5000),
                             cue_range_2 = seq(0, log10(6*(10^6)), by = log10(6*(10^6))/5000),
                             solver = "vode",
                             log_cue_1 = "log10",
                             log_cue_2 = "log10",
                             neg = T)
```

# trying alt where last round of optimization is started with 0.5 x 4
```{r}
ci_Ig_log_opt <- co_infection_opt_alt(parameters_cr = c(35.6294,	-65.6898,	-11.5609,	-52.0779),
                             limit = 0.01,
                             model = chabaudi_ci_clean,
                             immunity = "tsukushi",
                             parameters = parameters_tsukushi,
                             time_range = time_range,
                             cue_1 = "Ig1",
                             cue_2 = "Ig2",
                             cue_range_1 = seq(0, log10(6*(10^6)), by = log10(6*(10^6))/5000),
                             cue_range_2 = seq(0, log10(6*(10^6)), by = log10(6*(10^6))/5000),
                             solver = "vode",
                             log_cue_1 = "log10",
                             log_cue_2 = "log10")

# 2.189146 -5.450051  4.543525 -9.356682

# testing dynamics
test <- chabaudi_ci_clean(
  parameters_cr_1 = c( 2.189146, -5.450051,  4.543525, -9.356682),
                  parameters_cr_2 = c(2.189146, -5.450051,  4.543525, -9.356682),
                  immunity = "tsukushi",
                  parameters = parameters_tsukushi,
                  cue_1 = "Ig1",
                  cue_2 = "Ig2",
                  cue_range_1 = seq(0, log10(6*10^6), by = log10(6*10^6)/5000),
                  cue_range_2 = seq(0, log10(6*10^6), by = log10(6*10^6)/5000),
                  log_cue_1 = "log10",
                  log_cue_2 = "log10",
                  solver = "vode",
                  time_range = seq(0, 30, 0.001),
                  dyn = T)

# run preliminary random test. create df first. do 50 rep
test.df <- ci_opt.df[5,]
test.df$var1 <- 2.189146
test.df$var2 <- -5.45005
test.df$var3 <- 4.543525
test.df$var4 <- -9.356682
```

```{r}
check_ci_opt <- function(df){
  
  # get label
  label <- df$label_3
  
  # cluster initialization
  cl <- makeCluster(detectCores()); setDefaultCluster(cl = cl)
  registerDoParallel(cl)
  registerDoRNG(137)
  
  res <- foreach(i= 1:25, .packages = c("doParallel", "doRNG", "deSolve", "splines2", "stringr", "dplyr", "tidyr", "crone", "here")) %dorng% {
  # source function
  source(here("functions/chabaudi_ci_clean.R"))
    
  # parameters 
  parameters_tsukushi <- c(R1 = 8.89*10^6, # slightly higher
                lambda = 3.7*10^5,
                mu = 0.025, 
                p = 8*10^-6, # doubled form original
                alphag = 2, 
                beta = 5.721, 
                mum = 48, 
                mug = 4, 
                I0 = 43.85965, 
                Ig0 = 0, 
                a = 150, 
                b = 100, 
                sp = 1,
                psin = 16.69234,
                psiw = 0.8431785,
                phin = 0.03520591, 
                phiw = 550.842,
                iota = 2.18*(10^6),
                rho = 0.2627156)
  
  # read in df info
  if(stringr::str_detect(df$cue, "-i")){cue_1 = paste0(gsub("*-i", "", df$cue), "1")}
  if(stringr::str_detect(df$cue, "-i", negate = T)){cue_1 = df$cue}
  if(stringr::str_detect(df$cue, "-i")){cue_2 = paste0(gsub("*-i", "", df$cue), "2")}
  if(stringr::str_detect(df$cue, "-i", negate = T)){cue_2 = df$cue}
  if(stringr::str_detect(df$log, "log")){log_1 = "log10"}
  if(stringr::str_detect(df$log, "none")){log_1 = "none"}
  if(stringr::str_detect(df$log, "log")){log_2 = "log10"}
  if(stringr::str_detect(df$log, "none")){log_2 = "none"}
  par <- c(df$var1, df$var2, df$var3, df$var4)
  cue_range <- seq(df$low, df$high, by = df$by)
  
  # generate random par, bounds for parameters based on previous determined bounds
  par1 <- runif(1, -1, 1)
  par2 <- runif(1, -100, 100)
  par3 <- runif(1, -1000, 10000)
  par4 <- runif(1, -5000, 5000)
  
  par_rand <- c(par1, par2, par3, par4)
  
  # get fitness. 20 days simulation to cut down on computation time
  fitness <- chabaudi_ci_clean(parameters_cr_1 = par,
                  parameters_cr_2 = par_rand,
                  immunity = "tsukushi",
                  parameters = parameters_tsukushi,
                  cue_1 = cue_1,
                  cue_2 = cue_2,
                  cue_range_1 = cue_range,
                  cue_range_2 = cue_range,
                  log_cue_1 = log_1,
                  log_cue_2 = log_2,
                  solver = "vode",
                  time_range = seq(0, 30, by = 1e-3),
                  dyn = F)
  }
  stopCluster(cl)
  
  ## get fitness.df
  fitness.df <- do.call("rbind", res)

  ## rbind
  fitness.df <- as.data.frame(cbind(fitness.df, label = rep(label, nrow(fitness.df))))
  
  return(fitness.df)
}
```


#-----------------------#
# code for invasion analysis of ci
#-----------------------#
```{r}
ci_invasion_analysis <- function(df){
  
  # get mutant info (invader)
  mut_par <- c(df$var1, df$var2, df$var3, df$var4) ## mutant parameter
  if(stringr::str_detect(df$cue, "-i")){mut_cue = paste0(gsub("*-i", "", df$cue), "1")} ## mutant cue
  if(stringr::str_detect(df$cue, "-i", negate = T)){mut_cue = df$cue} ## mutant cue
  if(stringr::str_detect(df$log, "log")){mut_log = "log10"} ## mutant log
  if(stringr::str_detect(df$log, "none")){mut_log = "none"} ## mutant log
  mut_cue_range <- seq(df$low, df$high, by = df$by) ## mutant cue range
  
  # get resident info (being invaded)
  res_par <- c(df$var1_2, df$var2_2, df$var3_2, df$var4_2) ## resident parameter
  if(stringr::str_detect(df$cue_2, "-i")){res_cue = paste0(gsub("*-i", "", df$cue_2), "1")} ## resident cue
  if(stringr::str_detect(df$cue_2, "-i", negate = T)){res_cue = df$cue_2} ## resident cue
  if(stringr::str_detect(df$log_2, "log")){res_log = "log10"} ## resident log
  if(stringr::str_detect(df$log_2, "none")){res_log = "none"} ## resident log
  res_cue_range <- seq(df$low_2, df$high_2, by = df$by_2) ## resident cue range

  # get ids
  mut_id <- df$id
  res_i <- id$id_2
  
  # one way optimization
  ## start cluster
  cl <- makeCluster(detectCores()); setDefaultCluster(cl = cl)
  
  # start optimization LFBGS
  res <- optimParallel(
    par = mut_par,
    fn = chabaudi_ci_clean, 
    control = list(trace = 6, fnscale = -1),
    parameters_cr_2 = res_par,
    immunity = "tsukushi",
    parameters = parameters_tsukushi,
    time_range = seq(0, 20, by = 1e-3),
    cue_range_1 <- mut_cue_range,
    cue_range_2 <- res_cue_range,
    cue_1 = mut_cue,
    cue_2 = res_cue,
    log_cue_1 = mut_log,
    log_cue_2 = res_log,
    solver = "vode")
  
  # close cluster
  stopCluster(cl)
  
  # get model output
  fitness <- res$value ## fitness difference between mutant and residence
  mut_opt_par <- res$par ## optimized parameters of mutant
  
  # produce output
  output <- cbind.data.frame(mut_id = mut_id, res_id = res_id, 
                             fitness = fitness, 
                             mut_var1 = df$var1, mut_var2 = df$var2, mut_var3 = df$var3, mut_var4 = df$var4,
                             res_var1 = df$var1_2, res_var2 = df$var2_2, res_var3 = df$var3_2, res_var4 = df$var4_2,
                             mut_var1_opt = mut_opt_par[1], mut_var2_opt = mut_opt_par[2], mut_var3_opt = mut_opt_par[3], mut_var4_opt = mut_opt_par[4])
  
  return(output)
  
}
```

```{r}
source(here("functions/co_infection_opt_alt2.R"))
ci_Ig1_Ig2_log_opt <- co_infection_opt_alt(parameters_cr = c(22.08106, -47.95592, -12.97148,  19.60815),
                             limit = 0.01,
                             model = chabaudi_ci_clean,
                             immunity = "tsukushi",
                             parameters = parameters_tsukushi,
                             time_range = time_range,
                             cue_1 = "Ig1+Ig2",
                             cue_2 = "Ig1+Ig2",
                             cue_range_1 = seq(0, log10(6*(10^6)), by = (log10(6*(10^6)))/5000),
                             cue_range_2 = seq(0, log10(6*(10^6)), by = (log10(6*(10^6)))/5000),
                             solver = "vode",
                             log_cue_1 = "log10",
                             log_cue_2 = "log10")

# going to another local optimam
# 22.08106 -47.95592 -12.97148  19.60815


# trying DE
source(here("functions/co_infection_opt_do.R"))
ci_Ig1_Ig2_log_opt <- co_infection_opt_do(parameters_cr = c(22.08106, -47.95592, -12.97148,  19.60815),
                             limit = 0.01,
                             model = chabaudi_ci_clean,
                             immunity = "tsukushi",
                             parameters = parameters_tsukushi,
                             time_range = time_range,
                             cue_1 = "Ig1+Ig2",
                             cue_2 = "Ig1+Ig2",
                             cue_range_1 = seq(0, log10(6*(10^6)), by = (log10(6*(10^6)))/5000),
                             cue_range_2 = seq(0, log10(6*(10^6)), by = (log10(6*(10^6)))/5000),
                             solver = "vode",
                             log_cue_1 = "log10",
                             log_cue_2 = "log10",
                             neg = T)


test <- chabaudi_ci_clean(
  parameters_cr_1 = c(75.73915, -128.01549,  -41.16782,  -96.21549),
                  parameters_cr_2 = rep(2,4),
                  immunity = "tsukushi",
                             parameters = parameters_tsukushi,
                             time_range = time_range,
                             cue_1 = "Ig1+Ig2",
                             cue_2 = "Ig1+Ig2",
                             cue_range_1 = seq(0, log10(6*(10^6)), by = (log10(6*(10^6)))/5000),
                             cue_range_2 = seq(0, log10(6*(10^6)), by = (log10(6*(10^6)))/5000),
                             solver = "vode",
                             log_cue_1 = "log10",
                             log_cue_2 = "log10",
  dyn = T)

ggplot() +
  geom_line(data = test, aes(x = time, y = value, color = strain)) +
  facet_wrap(~variable_alt, scales = "free") +
  theme_bw()

```





